### ISSUE TITLE
Non accessible submodules

### ISSUE THREAD

**Issue by jorgefandinno** [potassco-asp-course/course#11]
The following submodules are not accessible

https://github.com/potassco-asp-course/meta-encoding
https://github.com/potassco-asp-course/multi-shot-solving
https://github.com/potassco-asp-course/theory-solving
https://github.com/potassco-asp-course/heuristic-driven-solving

**Comment by tortinator** [comment]
Where are `https` addresses used? I tried to avoid them, cf `.gitmodules.
Are you using `ssh keys` when using `github`?

**Comment by jorgefandinno** [comment]
> Where are `https` addresses used? I tried to avoid them, cf `.gitmodules`.
They are used in .gitmodules.

> Are you using `ssh keys` when using `github`?
I do.
> Also, I wonder what is different with these 4 modules..?
> SO I am a bit at a loss since I don't face this problem 😞
I cannot access those modules even in the browser.
If the url are correct, then I may not have access to them.
Are they public?

**Comment by tortinator** [comment]
Jackpot! :1st_place_medal:  I'm so sorry, I forgot to make them public :disappointed: 
I hope things work now that they are public.

BTW There are no `https` addresses for the modules in this organization. At least in the `.gitmodules` file I look at ... :confused: viz. `https://github.com/potassco-asp-course/course/blob/main/.gitmodules`

**Comment by tortinator** [comment]
BTW, would you like to become a member of this organization..?

**Comment by jorgefandinno** [comment]
> BTW, would you like to become a member of this organization..?

That would be great.

For a pull request, would you prefer that I create a new branch or that I make a fork. If the repository is public, it may make sense to use forks. That way, the working branches are private. What do you think?

**Comment by jorgefandinno** [comment]
> Jackpot! 🥇 I'm so sorry, I forgot to make them public 😞
> I hope things work now that they are public.
> 
> BTW There are no `https` addresses for the modules in this organization. At least in the `.gitmodules` file I look at ... 😕 viz. `https://github.com/potassco-asp-course/course/blob/main/.gitmodules`

When I enter I see 3 addresses with https:

https://github.com/krr-up/logos.git
https://github.com/krr-up/bibliography.git
https://github.com/krr-up/asp-macros.git

**Comment by tortinator** [comment]
Yes, but these belong to another organization, viz `krr-up`, where they are public.
All "local" repos are just linked relatively.
So do these things work with you now..?

**Comment by tortinator** [comment]
> > BTW, would you like to become a member of this organization..?
> 
> That would be great.

Will do at once

> For a pull request, would you prefer that I create a new branch or that I make a fork. If the repository is public, it may make sense to use forks. That way, the working branches are private. What do you think?

I do not know ...
