### ISSUE TITLE
asp-macros commit seems broken

### ISSUE THREAD

**Issue by jorgefandinno** [potassco-asp-course/course#12]
The asp-macros commit seems broken. It points to:

https://github.com/krr-up/asp-macros/tree/bc04a80607fbe091454cc8d734659a56dca32314

At least I cannot access it.

**Comment by tortinator** [comment]
`asp-macro` belongs to the `krr-up` organization where it is public - it's rather the hash that may be broken...?
Have you updated the submodules, perhaps this helps..?

**Comment by jorgefandinno** [comment]
> `asp-macro` belongs to the `krr-up` organization where it is public - it's rather the hash that may be broken...?
> Have you updated the submodules, perhaps this helps..?

Yes, I think that is the hash. I could repair it by doing a 

git reset --hard

I can make you a pull request if you want.

**Comment by tortinator** [comment]
I just updated teh submodule to teh newest version - does it work for you?

**Comment by jorgefandinno** [comment]
No, it is still broken

**Comment by tortinator** [comment]
No, it doesn't, but what I've checkout out works just fine ... I have no clue

**Comment by tortinator** [comment]
Ok ,I just checked out anew and got:

fatal: remote error: upload-pack: not our ref 357e0e22203fde7b379a609da1edcde5bca829e4
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'include/macros', but it did not contain 357e0e22203fde7b379a609da1edcde5bca829e4. Direct fetching of that commit failed.

**Comment by tortinator** [comment]
I do not get this on my laptop when cloning and updating but macros and all following stays empty ...

**Comment by jorgefandinno** [comment]
I send you a pull request with the current commit of the master.

**Comment by tortinator** [comment]
Sorry, I had to learn what I did wrong. Could you check out once more and try..? Muchas gracias!

**Comment by tortinator** [comment]
It works now (for me after cloning, updating submodules, etc) :nerd_face:

**Comment by jorgefandinno** [comment]
It works for me to.
Thanks
