### ISSUE TITLE
Cannot compile the latex source

### ISSUE THREAD

**Issue by dudaka** [potassco-asp-course/course#3]
Hi,

I cannot compile the latex source for slides.

This is the error I got when run `make` command
```
latexmk main.tex -pdf
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
Latexmk: applying rule 'biber main'...
Rule 'biber main': File changes, etc:
   Non-existent destination files:
      'main.bbl'
------------
Run number 1 of rule 'biber main'
------------
------------
Running 'biber  "main"'
------------
INFO - This is Biber 2.9
INFO - Logfile is 'main.blg'
ERROR - main.bcf is malformed, last biblatex run probably failed. Deleted main.bbl
INFO - ERRORS: 1
Biber error: [22] Utils.pm:185> ERROR - main.bcf is malformed, last biblatex run probably failed. Deleted main.bbl
Latexmk: Failed to find one or more biber source files:
  NONE
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  biber main: Could not find all biber source files for 'main'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 12
```

Hope someone can help me

Best regards,
Dung Ho

**Comment by tortinator** [comment]
First of all thanks for your interest! I'm not a biber expert. I'm running Biber 2.7 (debian) and 2.14 (ubuntu) and it works fine with me. Have you tried running things manually, viz `pdflatex` and `biblatex` ...? Sometimes cleaning all files up helps or running again after an error, since auxiliary files might be corrupted.

**Comment by dudaka** [comment]
Thank you for your response.
After hours, I found out that when cloning the course repository: `git clone --recursive`, all `.pdf` files are broken.
I successfully compile it now

**Comment by tortinator** [comment]
Happy to read this, keep enjoying ASP! @tortinator
